language: java
install: true

services:
  - docker

jdk:
  - oraclejdk8

script:
  - mkdir -p src/main/java
  - shopt -s globstar
  - docker run --rm
      -v $(pwd):$(pwd)
      -w $(pwd)
      znly/protoc
      --plugin=protoc-gen-grpc=/usr/bin/protoc-gen-grpc-java
      --java_out=./src/main/java
      --grpc_out=./src/main/java
      -I.
      ./hpi/**/*.proto
  - ./gradlew assemble

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    on:
      tags: true
