language: java
install: true

services:
  - docker

jdk:
  - oraclejdk8

script:
  - >
    docker run --rm
      -v $(pwd):$(pwd)
      -w $(pwd)
      znly/protoc
      --plugin=protoc-gen-grpc=/usr/bin/protoc-gen-grpc-java
      --java_out=./src/main/java
      --grpc_out=./src/main/java
      -I.
      ./hpi/**/*.proto
  - ./gradlew assemble -Puser=$BINTRAY_USER -Pkey=$BINTRAY_KEY

deploy:
  - provider: script
    script: ./gradlew bintrayUpload -Puser=$BINTRAY_USER -Pkey=$BINTRAY_KEY
    on:
      tags: true
