---
unicornVersion: "0.0.1"
type: "OTHER"
name: "hpi-cloud-apis"
description: "This repository contains the original interface definitions of public\
  \ HPI Cloud APIs that support the gRPC protocol. Reading the original interface\
  \ definitions can provide a better understanding of HPI Cloud APIs and help you\
  \ to utilize them more efficiently. You can also use these definitions with open\
  \ source tools to generate client libraries, documentation, and other artifacts."
version: "0.0.4"
githubName: "HPI-de/hpi-cloud-apis"
